name: Linux build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests this
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Versions
      run: |
          raku -v
          zip -v
          unzip -v
    - name: Runs tests
      id: tests
      uses: pmqs/raku-container-action@master
