name: Linux build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    name: "Raku: ${{ matrix.raku-version }}"

    strategy:
      matrix:
        raku-version:
          - latest
          - 2020.05

    container: jjmerelo/alpine-raku:${{ matrix.raku-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache
      id: my-cache
      uses: actions/cache@v2
      with:
        path: ~/${{ matrix.raku-version }}.cache

    - name: Raku version
      run: raku -v

      # Install zip for use in the test harness
    - name: Install zip
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: |
          apk add zip
          zip -v

      # Install unzip for use in the test harness
    - name: Install unzip
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: |
        apk add unzip
        unzip -v

    - name: Install dependencies
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: zef install --deps-only .

    - name: Refresh Cache Flag
      run: touch ~/${{ matrix.raku-version }}.cache

    - name: Run tests
      run: zef test --verbose .
