name: MacOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
          - windows-latest
      
        raku-release:
          - latest
          - 2019
                
    steps:
         
    - uses: actions/checkout@v2


    - name: Check Raku version
      run: |
        RakuVersion=$( perl - ${{ matrix.os }} ${{ matrix.release }} <<'EOM'

            use strict;
            use warnings;

            my %os_mapping = ( macos   => 'macos',
                               ubuntu  => 'linux',
                               windows => 'win'
                             ) ;

            my $os = shift ;
            my $version = shift ;

            $os =~ s/-.+$//;

            die "Unknown OS $os\n"
                if ! $os_mapping{$os} ;

            my %available;
            my @available;
            my @data = `curl -s --connect-timeout 5 https://rakudo.org/downloads/rakudo 2>/dev/null` ;

            die "Cannot fetch versions: $@\n"
                if $@;

            # get available versions for requested OS
            for my $line (@data)
            {
                next
                    unless $line =~ m#<a href=./dl/rakudo/rakudo-moar-([\d\.-]+?)-$os_mapping{$os}-x86_64#;

                push @available, $1;
            }

            my $max = 0;

            map { $max = $max < $_ ? $_ : $max }
            map { scalar split /\D+/, $_ }
            @available ;

            for my $v (@available)
            {
                my @bits = split /\D+/, $v ;
                push @bits, 0 for @bits .. $max ;
                my $numeric = join '', map { sprintf "%04d", $_ } @bits ;

                $available{$numeric} = $v;
            }

            if (lc $version eq 'latest')
            {
                print $available{ (sort keys %available)[-1] } . "\n";
            }
            else
            {
                my @got = grep { ! index $_, $version }
                          map  { $available{ $_ }     }
                          sort { $b <=> $a            }
                          keys %available ;

                die "Cannot find Raku version $version for $os\n"
                    if ! @got;

                print "$got[0]\n" ;
            }
            
        EOM
        )
        echo MATCH $RakuVersion
        echo "::set-env name=RAKU_VERSION::$RakuVersion"         
      shell: bash
      

    - name: Set Raku install Path in Unix format
      run: |
        echo "::set-env name=RAKU_INSTALL_PATH::$HOME/raku-${{ env.RAKU_VERSION }}"
        echo "::set-env name=RAKU_INSTALL_PATH_UX::$HOME/raku-${{ env.RAKU_VERSION }}"     
      shell: bash

    - name: Set Raku install Path in Windows format
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: |
        echo "::set-env name=RAKU_INSTALL_PATH::$HOME\raku-${{ env.RAKU_VERSION }}" 
              
    - name: Check for cached install for Raku ${{ env.RAKU_VERSION }}
      id: my-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.RAKU_INSTALL_PATH }}
        key: ${{ env.RAKU_VERSION }}-x12345
               
    - name: Install Raku ${{ env.RAKU_VERSION }} if not cached
      if: ${{ steps.my-cache.outputs.cache-hit != 'true' }}
      run: |
        mkdir -p ${{ env.RAKU_INSTALL_PATH_UX }}        
        cd ${{ env.RAKU_INSTALL_PATH_UX }}
        
        if [[ "${{ matrix.os }}" = windows* ]]
        then
            curl -s https://rakudo.org/dl/rakudo/rakudo-moar-${{ env.RAKU_VERSION }}-win-x86_64.zip >tmp.zip
            unzip tmp.zip
            rm tmp.zip
        elif  [[ "${{ matrix.os }}" = ubuntu* ]]
        then
            curl -s https://rakudo.org/dl/rakudo/rakudo-moar-${{ env.RAKU_VERSION}}-linux-x86_64.tar.gz | tar xzf - -C ${{ env.RAKU_INSTALL_PATH_UX }}
        else
            curl -s https://rakudo.org/dl/rakudo/rakudo-moar-${{ env.RAKU_VERSION }}-macos-x86_64.tar.gz | tar xzf - -C ${{ env.RAKU_INSTALL_PATH_UX }}            
        fi        
      shell: bash
                
      
    # Install zip for use in the test harness
    - name: Install zip (Windows)
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: |
        choco install zip
        zip -v
        
#     # Install unzip for use in the test harness  
#     - name: Install unzip (Windows)
#       if: ${{ startsWith(matrix.os, 'windows') }}      
#       run: |
#         choco install unzip
#         unzip -v
        
    - name: Get Path for Raku ${{ env.RAKU_VERSION }}
      run: |
        cd ${{ env.RAKU_INSTALL_PATH_UX }}
        BASE_RELEASE=$( ls )     
        #if [[ "${{ matrix.os }}" = windows* ]]
        #then        
          #echo "::set-env name=RAKU_BASE_PATH::${{ env.RAKU_INSTALL_PATH }}\\$BASE_RELEASE" 
        #else
          echo "::set-env name=RAKU_BASE_PATH::${{ env.RAKU_INSTALL_PATH }}/$BASE_RELEASE"         
        #fi
      shell: bash

              
    - name: Set Path for Raku ${{ env.RAKU_VERSION }} (Linux/MacOS)
      run: |        
        #if [[ "${{ matrix.os }}" = windows* ]]
        #then           
         # echo "::add-path::$RAKU_BASE_PATH\\bin"
         # echo "::add-path::$RAKU_BASE_PATH\\share\\perl6\\site\\bin"   
        #else
          echo "::add-path::$RAKU_BASE_PATH/bin"
          echo "::add-path::$RAKU_BASE_PATH/share/perl6/site/bin"           
        #fi
      shell: bash      
                
    - name: Raku ${{ env.RAKU_VERSION }} version
      run: raku -v
#       shell: bash

    - name: Zef version
      run: zef --version
#       shell: bash

    - name: Install module dependencies
      if: steps.my-cache.outputs.cache-hit != 'true'
      run:  zef install --deps-only .          
#       shell: bash

              
    - name: Run module tests
      run:  zef test --verbose .
#       shell: bash

        


