name: MacOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    env:
      PLATFORM: macos

      RAKU_RELEASE: "2020.06"
      RAKU_DOT_RELEASE: "-01"

      RAKU_INSTALL_PATH: $HOME/raku
      RAKULIB_PATH: $HOME/raku-lib

      RAKUDOLIB: inst#$RAKULIB_PATH
      PERL6LIB: inst#$RAKULIB_PATH

    steps:
    - uses: actions/checkout@v2

    - name: Check Cache
      id: my-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.RAKULIB_PATH }}
        key: ${{ env.PLATFORM }}-${{ env.RAKU_RELEASE }}${{ env.RAKU_DOT_RELEASE }}.cache

    # zip is used in the test harness
    - name: zip version
      run: zip -v

    # unzip is used in the test harness
    - name: unzip version
      run: unzip -v

    - name: Install Raku
      run: |
        mkdir -p ${{ env.RAKU_INSTALL_PATH }}
        wget -q https://rakudo.org/dl/rakudo/rakudo-moar-${{ env.RAKU_RELEASE }}${{ env.RAKU_DOT_RELEASE }}-${{ env.PLATFORM }}-x86_64.tar.gz -O $HOME/r.tar.gz
        tar xf ${{ env.HOME }}/r.tar.gz -C ${{ env.RAKU_INSTALL_PATH }}
        rm ${{ env.HOME }}/r.tar.gz

    - name: Set Path for Raku
      run: |
        echo "::add-path::${{ env.RAKU_INSTALL_PATH }}/rakudo-${{ env.RAKU_RELEASE }}/bin"
        echo "::add-path::${{ env.RAKU_INSTALL_PATH }}/rakudo-${{ env.RAKU_RELEASE }}/share/perl6/site/bin"
      
    - name: PATH
      run: echo ${{ env.PATH }}
            
    - name: Raku short version
      run: raku -v

    - name: Raku full version
      run: raku -V

    - name: Install Module dependencies
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ env.RAKULIB_PATH }}                       
        zef install --deps-only --install-to=${{ env.RAKUDOLIB }} .
        
    - name: Run tests
      run: zef test --verbose .

