name: MacOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # zip is used in the test narness
    - name: zip version
      run: zip -v

    # unzip is used in the test narness
    - name: unzip version
      run: unzip -v

    - name: Install Raku
      run: brew install rakudo-star

    - name: Raku version
      run: raku -v

    - name: Install Module dependencies
      run: zef install --deps-only .

    - name: Run tests
      run: zef test --verbose .
