name: MacOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    env:
      RAKUDOLIB: $HOME/raku-lib
      PERL6LIB: $HOME/raku-lib 
      RAKU_RELEASE: 2020.06-01

    steps:
    - uses: actions/checkout@v2

    - name: Check Cache
      id: my-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/raku-lib
          ~/raku-lib/**
        key: macos.cache

    # zip is used in the test harness
    - name: zip version
      run: zip -v

    # unzip is used in the test harness
    - name: unzip version
      run: unzip -v

    - name: Install Raku
#       if: steps.my-cache.outputs.cache-hit != 'true'
#       run: brew install rakudo-star
      run: |
        mkdir -p ~/raku                          
        wget -q https://rakudo.org/dl/rakudo/rakudo-moar-2020.06-01-macos-x86_64.tar.gz -O $HOME/r.tar.gz
        tar xf $HOME/r.tar.gz -C ~/raku
        rm $HOMEr.tar.gz

    - name: Set Path for Raku
      run: |
        echo "::add-path::$HOME/raku/rakudo-2020.06/bin"
        echo "::add-path::$HOME/raku/rakudo-2020.06/share/perl6/site/bin"
      
    - name: PATH
      run: echo $PATH
            
    - name: Raku short version
      run: raku -v

    - name: Raku full version
      run: raku -V

    - name: Install Module dependencies
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p $RAKUDOLIB                       
        zef install --deps-only --debug --verbose --install-to=$RAKUDOLIB .
        
    - name: Run tests
      run: zef test --verbose .
