name: MacOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Cache
      id: my-cache
      uses: actions/cache@v2
      with:
        path: ~/raku/**
        key: macos.cache

    # zip is used in the test harness
    - name: zip version
      run: zip -v

    # unzip is used in the test harness
    - name: unzip version
      run: unzip -v

    - name: Install Raku
      if: steps.my-cache.outputs.cache-hit != 'true'
#       run: brew install rakudo-star
      run: |
        pwd
        echo Home is ~
        echo GITHUB_WORKSPACE $GITHUB_WORKSPACE
        mkdir -p ~/tmp
        mkdir -p ~/raku        
        wget -q https://rakudo.org/dl/rakudo/rakudo-moar-2020.06-01-macos-x86_64.tar.gz -O ~/tmp/r.tar.gz
        tar xvf ~/tmp/r.tar.gz -C ~/raku
        rm ~/tmp/r.tar.gz

    - name: Set Path for Raku
      run: |
        echo ::add-path::~/raku/rakudo-2020.06/bin
        echo ::add-path::~/raku/rakudo-2020.06/share/perl6/site/bin
        echo -----------------
        ls -l ~
        echo ------------------
        ls -l ~/raku
        echo ----------------
        ls -l ~/raku/rakudo-2020.06/bin
        echo -------------
        ls -l ~/raku/rakudo-2020.06/share/perl6/site/bin
      
    - name: PATH
      run: echo $PATH
            
    - name: Raku short version
      run: ~/raku/rakudo-2020.06/bin/raku -v

    - name: Raku full version
      run: ~/raku/rakudo-2020.06/bin/raku -V

    - name: Install Module dependencies
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: ~/raku/rakudo-2020.06/share/perl6/site/bin/zef install --deps-only .

    - name: Run tests
      run: ~/raku/rakudo-2020.06/share/perl6/site/bin/zef test --verbose .
