name: MacOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
          - windows-latest
        raku-release:
          - 2020.06-01
          - 2020.05.1-01
                
    steps:
         
    - uses: actions/checkout@v2
             
    - name: Set Raku install Path (Linux/MacOS)
      if: ${{ ! startsWith(matrix.os, 'windows') }}
      run: |
        echo "::set-env name=RAKU_INSTALL_PATH::$HOME/raku-${{ matrix.raku-release }}"               
      
    - name: Set Raku install Path (Windoes)
      if: startsWith(matrix.os, 'windows')
      run: |
        echo "::set-env name=RAKU_INSTALL_PATH::$HOME\${{ matrix.raku-release }}"
      
    - name: Check Cache
      id: my-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.RAKU_INSTALL_PATH }}
        key: ${{ matrix.raku-release }}-x1
     
    - name: Install Raku (Linux/MacOS)
      if: ${{ ! startsWith(matrix.os, 'windows') && steps.my-cache.outputs.cache-hit != 'true' }}
      run: |
        mkdir -p ${{ env.RAKU_INSTALL_PATH }}
        if [[ "${{ matrix.os }}" = ubuntu* ]]
        then
            RAKU_OS=linux
        else
            RAKU_OS=macos
        fi
        wget -q https://rakudo.org/dl/rakudo/rakudo-moar-${{ matrix.raku-release }}-${RAKU_OS}-x86_64.tar.gz -O - | tar xzf - -C ${{ env.RAKU_INSTALL_PATH }}
        
        
    - name: Install Raku (Windows)
      if: ${{ startsWith(matrix.os, 'windows') && steps.my-cache.outputs.cache-hit != 'true' }}
      run: |
        mkdir ${{ env.RAKU_INSTALL_PATH }}
        wget -q https://rakudo.org/dl/rakudo/rakudo-moar-${{ matrix.raku-release }}-win-x86_64.tar.gz - | tar xzf - -C ${{ env.RAKU_INSTALL_PATH }}
   

    - name: Get Path for Raku (Linux/MacOS)
      if: ${{ ! startsWith(matrix.os, 'windows') }}
      run: |
        cd ${{ env.RAKU_INSTALL_PATH }}
        BASE_RELEASE=$( ls )       
        echo "::set-env name=RAKU_BASE_PATH::$HOME/raku-${{ matrix.raku-release }}/$BASE_RELEASE"               
              
    - name: Set Path for Raku (Linux/MacOS)
      if: ${{ ! startsWith(matrix.os, 'windows') }}
      run: |        
        echo "::add-path::$RAKU_BASE_PATH/bin"
        echo "::add-path::$RAKU_BASE_PATH/share/perl6/site/bin"     
        
    - name: Get Path for Raku (Windows)
      if: ${{ ! startsWith(matrix.os, 'windows') }}
      run: |
        cd ${{ env.RAKU_INSTALL_PATH }}
        $BASE_RELEASE = $pwd | Split-Path -Leaf 
        echo "::set-env name=RAKU_BASE_PATH::$HOME\raku-${{ matrix.raku-release }}\$BASE_RELEASE"               
              
    - name: Set Path for Raku (Windows)
      if: ${{ ! startsWith(matrix.os, 'windows') }}
      run: |        
        echo "::add-path::$RAKU_BASE_PATH\bin"
        echo "::add-path::$RAKU_BASE_PATH\share\perl6\site\bin"         
                
        
    - name: Raku short version
      run: raku -v

    - name: Raku full version
      run: raku -V

    - name: Install module dependencies
      if: steps.my-cache.outputs.cache-hit != 'true'
      run:  zef install --deps-only  .          
              
    - name: Run module tests
      run:  zef test --verbose .

        


