name: Test with Raku/setup-raku

on: [push, pull_request]

jobs:
  build:

    strategy:

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        raku-version:
          - latest
#           - 2020.06

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2
    - uses: Raku/setup-raku@v1
      with:
        raku-version: ${{ matrix.raku-version }}

    - name: Setup Raku cache
      uses: actions/cache@v2
      id: rakuCache
      with:
        path: raku-local
        key: ${{ runner.os }}-${{ matrix.raku-version }}

    - name: Raku ${{ env.RAKU_VERSION }} version
      run: raku -v

    - name: Install module dependencies
      if: steps.rakuCache.outputs.cache-hit != 'true'
      run:  |
        mkdir $GITHUB_WORKSPACE/raku-local
        zef install --install-to=inst#$GITHUB_WORKSPACE/raku-local --deps-only .

    - name: Set RAKULIB
      run:  |
        echo RAKULIB=inst#$GITHUB_WORKSPACE/raku-local >> $GITHUB_ENV
        echo PERL6LIB=inst#$GITHUB_WORKSPACE/raku-local >> $GITHUB_ENV

    - name: Run module tests
      run:  |
        echo --verbose >.proverc
        echo --verbose >_proverc
        zef test --verbose .