name: Raku Test

on: [push, pull_request]

jobs:
  build:

    strategy:

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        raku-version:
          - latest
#           - 2020.06

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2
    - uses: Raku/setup-raku@v1
      with:
        raku-version: ${{ matrix.raku-version }}

    - name: Raku ${{ env.RAKU_VERSION }} version
      run: raku -v

    - name: Install module dependencies
      run:  zef install --deps-only .

    - name: Run module tests
      run:  |
        echo --verbose >.proverc
        echo --verbose >_proverc
        zef test --verbose .
