name: Test with Raku/setup-raku

on: [push, pull_request]

jobs:
  build:

    strategy:

      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest

        raku-version:
          - latest
#           - 2020.06

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2
    - uses: Raku/setup-raku@v1
      with:
        raku-version: ${{ matrix.raku-version }}

    - name: Setup Raku cache
      uses: actions/cache@v2
      id: rakuCache
      with:
        path: .raku
        key: ${{ runner.os }}-${{ matrix.raku-version }}

    - name: Raku ${{ env.RAKU_VERSION }} version
      run: raku -v

    - name: Install module dependencies
      if: steps.rakuCache.outputs.cache-hit != 'true'
      run:  |
        cd $GITHUB_WORKSPACE
        mkdir .raku
        zef install --install-to=inst#$GITHUB_WORKSPACE/.raku --deps-only .

    - name: Run module tests
      env:
        RAKULIB: inst#$GITHUB_WORKSPACE/.raku
        PERL6LIB: inst#$GITHUB_WORKSPACE/.raku
      run:  |
        # echo --verbose >.proverc
        # echo --verbose >_proverc
        # RAKULIB=inst#$GITHUB_WORKSPACE/.raku $GITHUB_WORKSPACE/.raku/bin/prove6 -l -v t
        RAKULIB=inst#$GITHUB_WORKSPACE/.raku zef test --verbose .